# Generated by Django 4.2.2 on 2023-08-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_city', models.CharField(blank=True, max_length=40)),
                ('loc_district', models.CharField(blank=True, max_length=25)),
                ('loc_division', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Dinajpure', 'Dinajpure'), ('Mymanshingho', 'Mymanshigho')], default='Dha', max_length=13)),
            ],
            options={
                'db_table': 'LOCATIONS',
                'ordering': ['loc_id'],
                'permissions': [('add_loc', 'can add locations')],
            },
        ),
    ]
