# Generated by Django 4.2.2 on 2023-08-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('bran_id', models.AutoField(primary_key=True, serialize=False)),
                ('bran_name', models.CharField(blank=True, max_length=25)),
                ('bran_address', models.CharField(blank=True, max_length=100)),
                ('bran_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.locations')),
            ],
            options={
                'db_table': 'BRANCHES',
                'ordering': ['bran_id'],
                'permissions': [('add_bran', 'can add branch')],
            },
        ),
    ]
