# Generated by Django 4.2.2 on 2023-08-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_first_name', models.CharField(max_length=20)),
                ('emp_last_name', models.CharField(max_length=20)),
                ('emp_father_name', models.CharField(default='', max_length=15)),
                ('emp_mother_name', models.CharField(default='', max_length=15)),
                ('emp_married', models.CharField(choices=[('Married', 'married'), ('Single', 'single')], default='Single', max_length=8)),
                ('emp_address', models.TextField()),
                ('emp_gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='male', max_length=6)),
                ('emp_phone', models.IntegerField(blank=True, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_bod', models.DateField()),
                ('emp_salary', models.IntegerField()),
                ('emp_blood', models.CharField(max_length=4)),
                ('emp_photo', models.ImageField(blank=True, upload_to='emp')),
                ('emp_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.branches')),
                ('emp_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobs')),
                ('emp_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.emp')),
            ],
            options={
                'db_table': 'EMPLOYEES',
                'ordering': ['emp_id'],
                'permissions': [('add_employee', 'can add employees')],
            },
        ),
    ]
