# Generated by Django 4.2.2 on 2023-12-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_photo',
            field=models.ImageField(blank=True, upload_to='static/image/emp'),
        ),
    ]
